### ISSUE TITLE
Molly-guards

### ISSUE THREAD

**Issue by ewxrjk** [ewxrjk/vbig#2]
Several mistakes are very easy to make with `vbig`:

- writing to a device which isn't attached (any more). You end up with a regular file consuming all remaining space in `/dev`. `vbig` should require extra confirmation to write files in `/dev` which aren't device files.
- writing to a device which is in use. `vbig` should require extra confirmation to write to devices which `lsblk` (or similar on other platforms) says are in use.

Read-only operations don't need to check these things.

**Comment by mcv21** [comment]
Writing to a raw device that has an extant partition table and/or filesystem(s) on?
